/*
 * This file is generated by jOOQ.
*/
package com.sylvanaqua.farmhacker.database.tables;


import com.sylvanaqua.farmhacker.database.Farmhacker;
import com.sylvanaqua.farmhacker.database.tables.records.CatalogCategoryVwRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CatalogCategoryVw extends TableImpl<CatalogCategoryVwRecord> {

    private static final long serialVersionUID = -1746617508;

    /**
     * The reference instance of <code>farmhacker.catalog_category_vw</code>
     */
    public static final CatalogCategoryVw CATALOG_CATEGORY_VW = new CatalogCategoryVw();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CatalogCategoryVwRecord> getRecordType() {
        return CatalogCategoryVwRecord.class;
    }

    /**
     * The column <code>farmhacker.catalog_category_vw.category</code>.
     */
    public final TableField<CatalogCategoryVwRecord, String> CATEGORY = createField("category", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * Create a <code>farmhacker.catalog_category_vw</code> table reference
     */
    public CatalogCategoryVw() {
        this("catalog_category_vw", null);
    }

    /**
     * Create an aliased <code>farmhacker.catalog_category_vw</code> table reference
     */
    public CatalogCategoryVw(String alias) {
        this(alias, CATALOG_CATEGORY_VW);
    }

    private CatalogCategoryVw(String alias, Table<CatalogCategoryVwRecord> aliased) {
        this(alias, aliased, null);
    }

    private CatalogCategoryVw(String alias, Table<CatalogCategoryVwRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "VIEW");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Farmhacker.FARMHACKER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CatalogCategoryVw as(String alias) {
        return new CatalogCategoryVw(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CatalogCategoryVw rename(String name) {
        return new CatalogCategoryVw(name, null);
    }
}
