/*
 * This file is generated by jOOQ.
*/
package com.sylvanaqua.farmhacker.database.tables;


import com.sylvanaqua.farmhacker.database.Farmhacker;
import com.sylvanaqua.farmhacker.database.tables.records.CatalogInventoryVwRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CatalogInventoryVw extends TableImpl<CatalogInventoryVwRecord> {

    private static final long serialVersionUID = -955596039;

    /**
     * The reference instance of <code>farmhacker.catalog_inventory_vw</code>
     */
    public static final CatalogInventoryVw CATALOG_INVENTORY_VW = new CatalogInventoryVw();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CatalogInventoryVwRecord> getRecordType() {
        return CatalogInventoryVwRecord.class;
    }

    /**
     * The column <code>farmhacker.catalog_inventory_vw.id</code>.
     */
    public final TableField<CatalogInventoryVwRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>farmhacker.catalog_inventory_vw.category</code>.
     */
    public final TableField<CatalogInventoryVwRecord, String> CATEGORY = createField("category", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>farmhacker.catalog_inventory_vw.name</code>.
     */
    public final TableField<CatalogInventoryVwRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>farmhacker.catalog_inventory_vw.retail_price</code>.
     */
    public final TableField<CatalogInventoryVwRecord, Double> RETAIL_PRICE = createField("retail_price", org.jooq.impl.SQLDataType.FLOAT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0.00", org.jooq.impl.SQLDataType.FLOAT)), this, "");

    /**
     * The column <code>farmhacker.catalog_inventory_vw.wholesale_price</code>.
     */
    public final TableField<CatalogInventoryVwRecord, Double> WHOLESALE_PRICE = createField("wholesale_price", org.jooq.impl.SQLDataType.FLOAT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0.00", org.jooq.impl.SQLDataType.FLOAT)), this, "");

    /**
     * The column <code>farmhacker.catalog_inventory_vw.units_available</code>.
     */
    public final TableField<CatalogInventoryVwRecord, Long> UNITS_AVAILABLE = createField("units_available", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * Create a <code>farmhacker.catalog_inventory_vw</code> table reference
     */
    public CatalogInventoryVw() {
        this("catalog_inventory_vw", null);
    }

    /**
     * Create an aliased <code>farmhacker.catalog_inventory_vw</code> table reference
     */
    public CatalogInventoryVw(String alias) {
        this(alias, CATALOG_INVENTORY_VW);
    }

    private CatalogInventoryVw(String alias, Table<CatalogInventoryVwRecord> aliased) {
        this(alias, aliased, null);
    }

    private CatalogInventoryVw(String alias, Table<CatalogInventoryVwRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "VIEW");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Farmhacker.FARMHACKER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CatalogInventoryVw as(String alias) {
        return new CatalogInventoryVw(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CatalogInventoryVw rename(String name) {
        return new CatalogInventoryVw(name, null);
    }
}
