/*
 * This file is generated by jOOQ.
*/
package com.sylvanaqua.farmhacker.database.tables.records;


import com.sylvanaqua.farmhacker.database.tables.CatalogInventoryVw;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CatalogInventoryVwRecord extends TableRecordImpl<CatalogInventoryVwRecord> implements Record6<Integer, String, String, Double, Double, Long> {

    private static final long serialVersionUID = 1776356231;

    /**
     * Setter for <code>farmhacker.catalog_inventory_vw.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>farmhacker.catalog_inventory_vw.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>farmhacker.catalog_inventory_vw.category</code>.
     */
    public void setCategory(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>farmhacker.catalog_inventory_vw.category</code>.
     */
    public String getCategory() {
        return (String) get(1);
    }

    /**
     * Setter for <code>farmhacker.catalog_inventory_vw.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>farmhacker.catalog_inventory_vw.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>farmhacker.catalog_inventory_vw.retail_price</code>.
     */
    public void setRetailPrice(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>farmhacker.catalog_inventory_vw.retail_price</code>.
     */
    public Double getRetailPrice() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>farmhacker.catalog_inventory_vw.wholesale_price</code>.
     */
    public void setWholesalePrice(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>farmhacker.catalog_inventory_vw.wholesale_price</code>.
     */
    public Double getWholesalePrice() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>farmhacker.catalog_inventory_vw.units_available</code>.
     */
    public void setUnitsAvailable(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>farmhacker.catalog_inventory_vw.units_available</code>.
     */
    public Long getUnitsAvailable() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, Double, Double, Long> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, Double, Double, Long> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return CatalogInventoryVw.CATALOG_INVENTORY_VW.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return CatalogInventoryVw.CATALOG_INVENTORY_VW.CATEGORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return CatalogInventoryVw.CATALOG_INVENTORY_VW.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field4() {
        return CatalogInventoryVw.CATALOG_INVENTORY_VW.RETAIL_PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field5() {
        return CatalogInventoryVw.CATALOG_INVENTORY_VW.WHOLESALE_PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return CatalogInventoryVw.CATALOG_INVENTORY_VW.UNITS_AVAILABLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value4() {
        return getRetailPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value5() {
        return getWholesalePrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getUnitsAvailable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CatalogInventoryVwRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CatalogInventoryVwRecord value2(String value) {
        setCategory(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CatalogInventoryVwRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CatalogInventoryVwRecord value4(Double value) {
        setRetailPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CatalogInventoryVwRecord value5(Double value) {
        setWholesalePrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CatalogInventoryVwRecord value6(Long value) {
        setUnitsAvailable(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CatalogInventoryVwRecord values(Integer value1, String value2, String value3, Double value4, Double value5, Long value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CatalogInventoryVwRecord
     */
    public CatalogInventoryVwRecord() {
        super(CatalogInventoryVw.CATALOG_INVENTORY_VW);
    }

    /**
     * Create a detached, initialised CatalogInventoryVwRecord
     */
    public CatalogInventoryVwRecord(Integer id, String category, String name, Double retailPrice, Double wholesalePrice, Long unitsAvailable) {
        super(CatalogInventoryVw.CATALOG_INVENTORY_VW);

        set(0, id);
        set(1, category);
        set(2, name);
        set(3, retailPrice);
        set(4, wholesalePrice);
        set(5, unitsAvailable);
    }
}
