/*
 * This file is generated by jOOQ.
*/
package com.sylvanaqua.farmhacker.database.tables.records;


import com.sylvanaqua.farmhacker.database.tables.CatalogCategoryVw;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.TableRecordImpl;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CatalogCategoryVwRecord extends TableRecordImpl<CatalogCategoryVwRecord> implements Record1<String> {

    private static final long serialVersionUID = 305938519;

    /**
     * Setter for <code>farmhacker.catalog_category_vw.category</code>.
     */
    public void setCategory(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>farmhacker.catalog_category_vw.category</code>.
     */
    public String getCategory() {
        return (String) get(0);
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<String> valuesRow() {
        return (Row1) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return CatalogCategoryVw.CATALOG_CATEGORY_VW.CATEGORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getCategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CatalogCategoryVwRecord value1(String value) {
        setCategory(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CatalogCategoryVwRecord values(String value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CatalogCategoryVwRecord
     */
    public CatalogCategoryVwRecord() {
        super(CatalogCategoryVw.CATALOG_CATEGORY_VW);
    }

    /**
     * Create a detached, initialised CatalogCategoryVwRecord
     */
    public CatalogCategoryVwRecord(String category) {
        super(CatalogCategoryVw.CATALOG_CATEGORY_VW);

        set(0, category);
    }
}
