/*
 * This file is generated by jOOQ.
*/
package com.sylvanaqua.farmhacker.database.tables.records;


import com.sylvanaqua.farmhacker.database.tables.Inventory;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InventoryRecord extends UpdatableRecordImpl<InventoryRecord> implements Record5<Integer, Integer, Double, Timestamp, String> {

    private static final long serialVersionUID = -1789189550;

    /**
     * Setter for <code>farmhacker.inventory.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>farmhacker.inventory.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>farmhacker.inventory.catalog_id</code>.
     */
    public void setCatalogId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>farmhacker.inventory.catalog_id</code>.
     */
    public Integer getCatalogId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>farmhacker.inventory.measure</code>.
     */
    public void setMeasure(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>farmhacker.inventory.measure</code>.
     */
    public Double getMeasure() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>farmhacker.inventory.time_entered</code>.
     */
    public void setTimeEntered(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>farmhacker.inventory.time_entered</code>.
     */
    public Timestamp getTimeEntered() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>farmhacker.inventory.inventory_code</code>.
     */
    public void setInventoryCode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>farmhacker.inventory.inventory_code</code>.
     */
    public String getInventoryCode() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Double, Timestamp, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Double, Timestamp, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Inventory.INVENTORY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Inventory.INVENTORY.CATALOG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field3() {
        return Inventory.INVENTORY.MEASURE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Inventory.INVENTORY.TIME_ENTERED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Inventory.INVENTORY.INVENTORY_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getCatalogId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value3() {
        return getMeasure();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getTimeEntered();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getInventoryCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InventoryRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InventoryRecord value2(Integer value) {
        setCatalogId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InventoryRecord value3(Double value) {
        setMeasure(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InventoryRecord value4(Timestamp value) {
        setTimeEntered(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InventoryRecord value5(String value) {
        setInventoryCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InventoryRecord values(Integer value1, Integer value2, Double value3, Timestamp value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InventoryRecord
     */
    public InventoryRecord() {
        super(Inventory.INVENTORY);
    }

    /**
     * Create a detached, initialised InventoryRecord
     */
    public InventoryRecord(Integer id, Integer catalogId, Double measure, Timestamp timeEntered, String inventoryCode) {
        super(Inventory.INVENTORY);

        set(0, id);
        set(1, catalogId);
        set(2, measure);
        set(3, timeEntered);
        set(4, inventoryCode);
    }
}
