/*
 * This file is generated by jOOQ.
*/
package com.sylvanaqua.farmhacker.database.tables.records;


import com.sylvanaqua.farmhacker.database.tables.InventoryValue;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InventoryValueRecord extends TableRecordImpl<InventoryValueRecord> implements Record5<String, String, Double, Double, Double> {

    private static final long serialVersionUID = -2051518632;

    /**
     * Setter for <code>farmhacker.inventory_value.category</code>.
     */
    public void setCategory(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>farmhacker.inventory_value.category</code>.
     */
    public String getCategory() {
        return (String) get(0);
    }

    /**
     * Setter for <code>farmhacker.inventory_value.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>farmhacker.inventory_value.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>farmhacker.inventory_value.SUM(inventory.measure)</code>.
     */
    public void setSum_28inventoryMeasure_29(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>farmhacker.inventory_value.SUM(inventory.measure)</code>.
     */
    public Double getSum_28inventoryMeasure_29() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>farmhacker.inventory_value.retail_value</code>.
     */
    public void setRetailValue(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>farmhacker.inventory_value.retail_value</code>.
     */
    public Double getRetailValue() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>farmhacker.inventory_value.wholesale_value</code>.
     */
    public void setWholesaleValue(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>farmhacker.inventory_value.wholesale_value</code>.
     */
    public Double getWholesaleValue() {
        return (Double) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, Double, Double, Double> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, Double, Double, Double> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return InventoryValue.INVENTORY_VALUE.CATEGORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return InventoryValue.INVENTORY_VALUE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field3() {
        return InventoryValue.INVENTORY_VALUE.SUM_28INVENTORY_MEASURE_29;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field4() {
        return InventoryValue.INVENTORY_VALUE.RETAIL_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field5() {
        return InventoryValue.INVENTORY_VALUE.WHOLESALE_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getCategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value3() {
        return getSum_28inventoryMeasure_29();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value4() {
        return getRetailValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value5() {
        return getWholesaleValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InventoryValueRecord value1(String value) {
        setCategory(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InventoryValueRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InventoryValueRecord value3(Double value) {
        setSum_28inventoryMeasure_29(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InventoryValueRecord value4(Double value) {
        setRetailValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InventoryValueRecord value5(Double value) {
        setWholesaleValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InventoryValueRecord values(String value1, String value2, Double value3, Double value4, Double value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InventoryValueRecord
     */
    public InventoryValueRecord() {
        super(InventoryValue.INVENTORY_VALUE);
    }

    /**
     * Create a detached, initialised InventoryValueRecord
     */
    public InventoryValueRecord(String category, String name, Double sum_28inventoryMeasure_29, Double retailValue, Double wholesaleValue) {
        super(InventoryValue.INVENTORY_VALUE);

        set(0, category);
        set(1, name);
        set(2, sum_28inventoryMeasure_29);
        set(3, retailValue);
        set(4, wholesaleValue);
    }
}
