/*
 * This file is generated by jOOQ.
*/
package com.sylvanaqua.farmhacker.database.tables.records;


import com.sylvanaqua.farmhacker.database.tables.MarketZip;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MarketZipRecord extends UpdatableRecordImpl<MarketZipRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = -1133652398;

    /**
     * Setter for <code>farmhacker.market_zip.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>farmhacker.market_zip.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>farmhacker.market_zip.market_id</code>.
     */
    public void setMarketId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>farmhacker.market_zip.market_id</code>.
     */
    public Integer getMarketId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>farmhacker.market_zip.postal_code</code>.
     */
    public void setPostalCode(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>farmhacker.market_zip.postal_code</code>.
     */
    public Integer getPostalCode() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return MarketZip.MARKET_ZIP.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return MarketZip.MARKET_ZIP.MARKET_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return MarketZip.MARKET_ZIP.POSTAL_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getMarketId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getPostalCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MarketZipRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MarketZipRecord value2(Integer value) {
        setMarketId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MarketZipRecord value3(Integer value) {
        setPostalCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MarketZipRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MarketZipRecord
     */
    public MarketZipRecord() {
        super(MarketZip.MARKET_ZIP);
    }

    /**
     * Create a detached, initialised MarketZipRecord
     */
    public MarketZipRecord(Integer id, Integer marketId, Integer postalCode) {
        super(MarketZip.MARKET_ZIP);

        set(0, id);
        set(1, marketId);
        set(2, postalCode);
    }
}
