
CREATE TABLE IF NOT EXISTS inventory (
	id MEDIUMINT NOT NULL AUTO_INCREMENT,
	category VARCHAR(50) NOT NULL,
	name VARCHAR(100) NOT NULL,
	quantity SMALLINT DEFAULT 0 NOT NULL,
	retail_price FLOAT(3,2) DEFAULT 0.00 NOT NULL,
	wholesale_price FLOAT(3,2) DEFAULT 0.00 NOT NULL,
	PRIMARY KEY (id)
);
